"use strict";
(function(){
const $=id=>document.getElementById(id), ADMIN_UID=window.ADMIN_UID||"FhVg6EpradNuZhUd63Cd4grkLbk2";
const load=$("pantallaCarga"), login=$("loginContainer"), admin=$("adminContainer"), form=$("loginForm"), email=$("email"), pass=$("password"), remember=$("recordarSesion"), btn=$("btnLogin"), logout=$("btnCerrarSesion"), err=$("mensajeError");
let authChecked=false, datosRifa=new Map(), unsubscribe=null, tipo="normal";
function showLogin(){load?.classList.add("oculto");admin?.classList.add("oculto");login?.classList.remove("oculto")}
function showAdmin(u){load?.classList.add("oculto");login?.classList.add("oculto");admin?.classList.remove("oculto");$("usuarioActual").textContent=u.email||"Administrador";iniciarPanel()}
function error(m){if(!err)return;err.textContent=m;err.classList.remove("oculto")}
function clearError(){err?.classList.add("oculto")}
$("btnMostrarPassword")?.addEventListener("click",()=>{pass.type=pass.type==="password"?"text":"password"});
form?.addEventListener("submit",async e=>{e.preventDefault();clearError();btn.disabled=true;btn.textContent="⏳ Verificando...";try{await firebase.auth().setPersistence(remember?.checked?firebase.auth.Auth.Persistence.LOCAL:firebase.auth.Auth.Persistence.SESSION);const r=await firebase.auth().signInWithEmailAndPassword(email.value.trim(),pass.value);if(!r.user||r.user.uid!==ADMIN_UID){await firebase.auth().signOut();throw new Error("Esta cuenta no tiene permisos de administrador.")}}catch(e){const m={"auth/invalid-email":"El correo electrónico no es válido.","auth/user-not-found":"El correo o la contraseña son incorrectos.","auth/wrong-password":"El correo o la contraseña son incorrectos.","auth/invalid-credential":"El correo o la contraseña son incorrectos.","auth/too-many-requests":"Demasiados intentos. Espera un momento."};error(m[e.code]||e.message||"No fue posible iniciar sesión.")}finally{btn.disabled=false;btn.textContent="🔐 Iniciar sesión"}});
logout?.addEventListener("click",async()=>{logout.disabled=true;logout.textContent="⏳ Cerrando...";try{if(unsubscribe)unsubscribe();await firebase.auth().signOut()}catch(e){error("No fue posible cerrar la sesión.")}finally{logout.disabled=false;logout.textContent="🚪 Cerrar sesión"}});
function paneles(){document.querySelectorAll(".admin-opcion").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".admin-opcion").forEach(x=>x.classList.remove("activo"));b.classList.add("activo");document.querySelectorAll(".admin-panel").forEach(p=>p.classList.add("oculto"));$("panel-"+b.dataset.panel)?.classList.remove("oculto")}))}
function fecha(v){if(!v)return "—";if(v.toDate)return v.toDate().toLocaleString("es-CO");const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString("es-CO")}
function escapeHtml(s){return String(s??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderNumeros(){const filtro=$("filtroNumeros")?.value||"todos", arr=[...datosRifa.entries()].sort((a,b)=>a[0].localeCompare(b[0],undefined,{numeric:true}));let rows=arr.filter(([n,d])=>filtro==="todos"||(filtro==="reservados"&&!d.pagado)||(filtro==="pagados"&&d.pagado)||(filtro==="disponibles"&&!d));if(tipo==="normal"&&filtro==="disponibles"){const usados=new Set(datosRifa.keys());rows=[];for(let i=0;i<100;i++){let n=String(i).padStart(2,"0");if(!usados.has(n))rows.push([n,null])}}const el=$("listaNumeros");if(!rows.length){el.innerHTML='<div class="vacio">No hay registros para este filtro.</div>';return}el.innerHTML='<table><thead><tr><th>Número</th><th>Cliente</th><th>Teléfono</th><th>Estado</th><th>Fecha</th><th>Acción</th></tr></thead><tbody>'+rows.map(([n,d])=>`<tr><td><b>${escapeHtml(n)}</b></td><td>${escapeHtml(d?.nombre||"—")}</td><td>${escapeHtml(d?.telefono||"—")}</td><td><span class="estado ${d?(d.pagado?'pagado':'reservado'):'disponible'}">${d?(d.pagado?'PAGADO':'RESERVADO'):'DISPONIBLE'}</span></td><td>${fecha(d?.fecha)}</td><td>${d?`<button class="btn-danger btn-liberar" data-id="${escapeHtml(n)}">🗑️ Liberar</button>`:'—'}</td></tr>`).join('')+'</tbody></table>'}
function renderPagos(){const f=$("filtroPagos")?.value||"todos", arr=[...datosRifa.entries()].filter(([n,d])=>f==="todos"||(f==="pendientes"&&!d.pagado)||(f==="pagados"&&d.pagado)).sort((a,b)=>a[0].localeCompare(b[0],undefined,{numeric:true}));const el=$("listaPagos");if(!arr.length){el.innerHTML='<div class="vacio">No hay pagos para este filtro.</div>';return}el.innerHTML='<table><thead><tr><th>Número</th><th>Cliente</th><th>Teléfono</th><th>Estado</th><th>Acción</th></tr></thead><tbody>'+arr.map(([n,d])=>`<tr><td><b>${escapeHtml(n)}</b></td><td>${escapeHtml(d.nombre)}</td><td>${escapeHtml(d.telefono)}</td><td><span class="estado ${d.pagado?'pagado':'reservado'}">${d.pagado?'PAGADO':'PENDIENTE'}</span></td><td><button class="btn-primary btn-pago" data-id="${escapeHtml(n)}">${d.pagado?'↩️ Marcar pendiente':'✅ Marcar pagado'}</button></td></tr>`).join('')+'</tbody></table>'}
function renderCompradores(){const q=($("buscarComprador")?.value||"").toLowerCase().trim(), groups={};datosRifa.forEach((d,n)=>{const key=(d.telefono||d.nombre||n).toString();groups[key]??={nombre:d.nombre||"—",telefono:d.telefono||"—",nums:[],pagados:0,fecha:d.fecha};groups[key].nums.push(n);if(d.pagado)groups[key].pagados++});let arr=Object.values(groups).filter(x=>!q||x.nombre.toLowerCase().includes(q)||x.telefono.toLowerCase().includes(q));const el=$("listaCompradores");if(!arr.length){el.innerHTML='<div class="vacio">No hay compradores.</div>';return}el.innerHTML='<table><thead><tr><th>Nombre</th><th>Teléfono</th><th>Números</th><th>Pagados</th><th>Última fecha</th></tr></thead><tbody>'+arr.map(x=>`<tr><td><b>${escapeHtml(x.nombre)}</b></td><td>${escapeHtml(x.telefono)}</td><td>${escapeHtml(x.nums.sort().join(', '))}</td><td>${x.pagados}/${x.nums.length}</td><td>${fecha(x.fecha)}</td></tr>`).join('')+'</tbody></table>'}
function render(){renderNumeros();renderPagos();renderCompradores();const reserv=datosRifa.size,pag=[...datosRifa.values()].filter(x=>x.pagado).length,total=tipo==="mini"?10:tipo==="combo"?50:100;$("statDisponibles").textContent=Math.max(0,total-reserv);$("statReservados").textContent=reserv-pag;$("statPagados").textContent=pag}
async function cargarConfig(){const [d,t,x]=await Promise.all([db.collection("config").doc("datos").get(),db.collection("config").doc("talonario").get(),db.collection("config").doc("texto").get()]);const datos=d.exists?d.data():{};tipo=t.exists?(t.data().tipo||"normal"):"normal";$("cfgNequi").value=datos.nequi||"3003704654";$("cfgWhatsapp").value=datos.whatsapp||"3003704654";$("cfgTipo").value=tipo;$("cfgHtml").value=x.exists?(x.data().html||""):""}
async function guardarConfig(e){e.preventDefault();const b=$("btnGuardarConfig");b.disabled=true;b.textContent="⏳ Guardando...";try{await db.collection("config").doc("datos").set({nequi:$("cfgNequi").value.trim(),whatsapp:$("cfgWhatsapp").value.trim()},{merge:true});await db.collection("config").doc("talonario").set({tipo:$("cfgTipo").value},{merge:true});await db.collection("config").doc("texto").set({html:$("cfgHtml").value},{merge:true});tipo=$("cfgTipo").value;render();alert("Configuración guardada correctamente.")}catch(e){console.error(e);alert("No se pudo guardar. Revisa las reglas de Firestore.")}finally{b.disabled=false;b.textContent="💾 Guardar configuración"}}
async function liberar(id){if(!confirm(`¿Liberar el número ${id}? Esta acción elimina la reserva.`))return;try{await db.collection("rifa").doc(id).delete()}catch(e){console.error(e);alert("No se pudo liberar. Revisa las reglas de Firestore.")}}
async function cambiarPago(id){const d=datosRifa.get(id);if(!d)return;try{await db.collection("rifa").doc(id).update({pagado:d.pagado!==true})}catch(e){console.error(e);alert("No se pudo actualizar el pago. Revisa las reglas de Firestore.")}}
function eventos(){paneles();$("filtroNumeros")?.addEventListener("change",renderNumeros);$("filtroPagos")?.addEventListener("change",renderPagos);$("buscarComprador")?.addEventListener("input",renderCompradores);$("configForm")?.addEventListener("submit",guardarConfig);$("btnRecargarConfig")?.addEventListener("click",()=>cargarConfig().catch(console.error));$("btnActualizar")?.addEventListener("click",()=>render());document.addEventListener("click",e=>{const l=e.target.closest(".btn-liberar"),p=e.target.closest(".btn-pago");if(l)liberar(l.dataset.id);if(p)cambiarPago(p.dataset.id)})}
function iniciarPanel(){if(unsubscribe)return;eventos();cargarConfig().catch(e=>console.error(e));unsubscribe=db.collection("rifa").onSnapshot(s=>{datosRifa.clear();s.forEach(d=>datosRifa.set(d.id,d.data()));render()},e=>{console.error(e);$("mensajeAdmin").textContent="❌ Error leyendo Firestore: "+(e.message||"sin detalles")})}
if(typeof firebase==="undefined"||!firebase.auth){showLogin();error("Firebase Authentication no está disponible.");return}
firebase.auth().onAuthStateChanged(async u=>{authChecked=true;if(!u){showLogin();return}if(u.uid!==ADMIN_UID){await firebase.auth().signOut();showLogin();error("Esta cuenta no tiene permisos de administrador.");return}showAdmin(u)});setTimeout(()=>{if(!authChecked)showLogin()},7000);
})();
