"use strict";
(function(){
const $=id=>document.getElementById(id), ADMIN_UID=window.ADMIN_UID||"FhVg6EpradNuZhUd63Cd4grkLbk2";
const load=$("pantallaCarga"),login=$("loginContainer"),admin=$("adminContainer"),form=$("loginForm"),email=$("email"),pass=$("password"),remember=$("recordarSesion"),btn=$("btnLogin"),logout=$("btnCerrarSesion"),err=$("mensajeError");
let authChecked=false,datosRifa=new Map(),unsubscribe=null,tipo="normal",comboLista=[];
function coleccionRifa(){if(tipo==="mini")return "rifa_mini";if(tipo==="combo")return "rifa_combo";return "rifa_normal";}
function detenerEscucha(){if(unsubscribe){unsubscribe();unsubscribe=null;}}
function escucharRifa(){detenerEscucha();unsubscribe=db.collection(coleccionRifa()).onSnapshot(s=>{datosRifa.clear();s.forEach(d=>datosRifa.set(d.id,d.data()));render();mostrarResultadoGanador()},e=>{console.error(e);msg("❌ Error leyendo Firestore: "+(e.message||"sin detalles"),"error")});}
function showLogin(){load?.classList.add("oculto");admin?.classList.add("oculto");login?.classList.remove("oculto")}
function showAdmin(u){load?.classList.add("oculto");login?.classList.add("oculto");admin?.classList.remove("oculto");$("usuarioActual").textContent=u.email||"Administrador";iniciarPanel()}
function error(m){if(!err)return;err.textContent=m;err.classList.remove("oculto")}
function clearError(){err?.classList.add("oculto")}
function msg(m,t="ok"){const x=$("mensajeAdmin");if(x){x.textContent=m;x.className="mensaje-admin "+t}}
function fecha(v){if(!v)return "—";if(v.toDate)return v.toDate().toLocaleString("es-CO");const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString("es-CO")}
function esc(s){return String(s??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$("btnMostrarPassword")?.addEventListener("click",()=>{pass.type=pass.type==="password"?"text":"password"});
form?.addEventListener("submit",async e=>{e.preventDefault();clearError();btn.disabled=true;btn.textContent="⏳ Verificando...";try{await firebase.auth().setPersistence(remember?.checked?firebase.auth.Auth.Persistence.LOCAL:firebase.auth.Auth.Persistence.SESSION);const r=await firebase.auth().signInWithEmailAndPassword(email.value.trim(),pass.value);if(!r.user||r.user.uid!==ADMIN_UID){await firebase.auth().signOut();throw new Error("Esta cuenta no tiene permisos de administrador.")}}catch(e){const m={"auth/invalid-email":"El correo electrónico no es válido.","auth/user-not-found":"El correo o la contraseña son incorrectos.","auth/wrong-password":"El correo o la contraseña son incorrectos.","auth/invalid-credential":"El correo o la contraseña son incorrectos.","auth/too-many-requests":"Demasiados intentos. Espera un momento."};error(m[e.code]||e.message||"No fue posible iniciar sesión.")}finally{btn.disabled=false;btn.textContent="🔐 Iniciar sesión"}});
logout?.addEventListener("click",async()=>{logout.disabled=true;logout.textContent="⏳ Cerrando...";try{if(unsubscribe)unsubscribe();await firebase.auth().signOut()}finally{logout.disabled=false;logout.textContent="🚪 Cerrar sesión"}});
function paneles(){document.querySelectorAll(".admin-opcion").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".admin-opcion").forEach(x=>x.classList.remove("activo"));b.classList.add("activo");document.querySelectorAll(".admin-panel").forEach(p=>p.classList.add("oculto"));$("panel-"+b.dataset.panel)?.classList.remove("oculto")}))}
function renderNumeros(){const f=$("filtroNumeros")?.value||"todos";let rows=[];if(f==="disponibles"){if(tipo==="combo"){comboLista.forEach(n=>{if(!datosRifa.has(n))rows.push([n,null])})}else{const total=tipo==="mini"?10:100;for(let i=0;i<total;i++){const n=tipo==="mini"?String(i):String(i).padStart(2,"0");if(!datosRifa.has(n))rows.push([n,null])}}}else{rows=[...datosRifa.entries()].filter(([n,d])=>f==="todos"||(f==="reservados"&&!d.pagado)||(f==="pagados"&&d.pagado)).sort((a,b)=>a[0].localeCompare(b[0],undefined,{numeric:true}))}const el=$("listaNumeros");if(!rows.length){el.innerHTML='<div class="vacio">No hay registros para este filtro.</div>';return}el.innerHTML='<table><thead><tr><th>Número/Combo</th><th>Cliente</th><th>Teléfono</th><th>Estado</th><th>Fecha</th><th>Acción</th></tr></thead><tbody>'+rows.map(([n,d])=>`<tr><td><b>${esc(n)}</b></td><td>${esc(d?.nombre||"—")}</td><td>${esc(d?.telefono||"—")}</td><td><span class="estado ${d?(d.pagado?'pagado':'reservado'):'disponible'}">${d?(d.pagado?'PAGADO':'RESERVADO'):'DISPONIBLE'}</span></td><td>${fecha(d?.fecha)}</td><td>${d?`<button class="btn-danger btn-liberar" data-id="${esc(n)}">🗑️ Liberar</button>`:'—'}</td></tr>`).join('')+'</tbody></table>'}
function renderPagos(){const f=$("filtroPagos")?.value||"todos",arr=[...datosRifa.entries()].filter(([n,d])=>f==="todos"||(f==="pendientes"&&!d.pagado)||(f==="pagados"&&d.pagado)).sort((a,b)=>a[0].localeCompare(b[0],undefined,{numeric:true}));const el=$("listaPagos");if(!arr.length){el.innerHTML='<div class="vacio">No hay pagos para este filtro.</div>';return}el.innerHTML='<table><thead><tr><th>Número/Combo</th><th>Cliente</th><th>Teléfono</th><th>Estado</th><th>Acción</th></tr></thead><tbody>'+arr.map(([n,d])=>`<tr><td><b>${esc(n)}</b></td><td>${esc(d.nombre)}</td><td>${esc(d.telefono)}</td><td><span class="estado ${d.pagado?'pagado':'reservado'}">${d.pagado?'PAGADO':'PENDIENTE'}</span></td><td><button class="btn-primary btn-pago" data-id="${esc(n)}">${d.pagado?'↩️ Marcar pendiente':'✅ Marcar pagado'}</button></td></tr>`).join('')+'</tbody></table>'}
function renderCompradores(){const q=($("buscarComprador")?.value||"").toLowerCase().trim(),groups={};datosRifa.forEach((d,n)=>{const k=(d.telefono||d.nombre||n).toString();groups[k]??={nombre:d.nombre||"—",telefono:d.telefono||"—",nums:[],pagados:0,fecha:d.fecha};groups[k].nums.push(n);if(d.pagado)groups[k].pagados++});const arr=Object.values(groups).filter(x=>!q||x.nombre.toLowerCase().includes(q)||x.telefono.toLowerCase().includes(q)),el=$("listaCompradores");if(!arr.length){el.innerHTML='<div class="vacio">No hay compradores.</div>';return}el.innerHTML='<table><thead><tr><th>Nombre</th><th>Teléfono</th><th>Números</th><th>Pagados</th><th>Última fecha</th></tr></thead><tbody>'+arr.map(x=>`<tr><td><b>${esc(x.nombre)}</b></td><td>${esc(x.telefono)}</td><td>${esc(x.nums.sort().join(', '))}</td><td>${x.pagados}/${x.nums.length}</td><td>${fecha(x.fecha)}</td></tr>`).join('')+'</tbody></table>'}
function render(){renderNumeros();renderPagos();renderCompradores();const reserv=datosRifa.size,pag=[...datosRifa.values()].filter(x=>x.pagado).length,total=tipo==="mini"?10:tipo==="combo"?50:100;$("statDisponibles").textContent=Math.max(0,total-reserv);$("statReservados").textContent=reserv-pag;$("statPagados").textContent=pag}
async function cargarConfig(){const[d,t,x,p,c]=await Promise.all([db.collection("config").doc("datos").get(),db.collection("config").doc("talonario").get(),db.collection("config").doc("texto").get(),db.collection("config").doc("premios").get(),db.collection("config").doc("combos").get()]);const datos=d.exists?d.data():{};tipo=t.exists?(t.data().tipo||"normal"):"normal";$("cfgNequi").value=datos.nequi||"3003704654";$("cfgWhatsapp").value=datos.whatsapp||"3003704654";$("cfgTipo").value=tipo;$("cfgHtml").value=x.exists?(x.data().html||""):"";comboLista=c.exists&&Array.isArray(c.data().lista)?c.data().lista:[];const pr=p.exists?p.data():{};$("cfgGanador").value=pr.ganador||"";$("cfgPremioPrimeras").value=pr.primeras??"";$("cfgPremioMedio").value=pr.medio??"";$("cfgPremioUltimas").value=pr.ultimas??"";mostrarResultadoGanador()}
async function guardarConfig(e){e.preventDefault();const b=$("btnGuardarConfig");b.disabled=true;b.textContent="⏳ Guardando...";try{await db.collection("config").doc("datos").set({nequi:$("cfgNequi").value.trim(),whatsapp:$("cfgWhatsapp").value.trim()},{merge:true});await db.collection("config").doc("talonario").set({tipo:$("cfgTipo").value},{merge:true});await db.collection("config").doc("texto").set({html:$("cfgHtml").value},{merge:true});await db.collection("config").doc("premios").set({ganador:$("cfgGanador").value.replace(/\D/g,"").slice(0,4),primeras:$("cfgPremioPrimeras").value.trim(),medio:$("cfgPremioMedio").value.trim(),ultimas:$("cfgPremioUltimas").value.trim()},{merge:true});tipo=$("cfgTipo").value;escucharRifa();render();msg("✅ Configuración guardada correctamente.")}catch(e){console.error(e);msg("❌ No se pudo guardar. Revisa las reglas de Firestore.","error")}finally{b.disabled=false;b.textContent="💾 Guardar configuración"}}
async function liberar(id){if(!confirm(`¿Liberar ${id}? Esta acción elimina la reserva.`))return;try{await db.collection(coleccionRifa()).doc(id).delete();msg(`✅ ${id} fue liberado.`)}catch(e){console.error(e);msg("❌ No se pudo liberar.","error")}}
async function cambiarPago(id){const d=datosRifa.get(id);if(!d)return;try{await db.collection(coleccionRifa()).doc(id).update({pagado:d.pagado!==true});msg(d.pagado?`↩️ ${id} volvió a pendiente.`:`✅ ${id} marcado como pagado.`)}catch(e){console.error(e);msg("❌ No se pudo actualizar el pago.","error")}}
function partesGanador(v){const s=String(v||"").replace(/\D/g,"").padStart(4,"0").slice(-4);return{ganador:s,primeras:s.slice(0,2),medio:s.slice(1,3),ultimas:s.slice(2,4)}}
function encontrarReserva(num){if(datosRifa.has(num))return datosRifa.get(num);for(const[dkey,d]of datosRifa.entries()){const partes=String(dkey).split(/\s*-\s*/);if(partes.includes(num))return d}return null}
function mostrarResultadoGanador(){const v=$("cfgGanador")?.value;if(!v)return;const p=partesGanador(v),out=$("resultadoGanador");if(!out)return;const a=encontrarReserva(p.primeras),b=encontrarReserva(p.medio),c=encontrarReserva(p.ultimas);out.innerHTML=`<div class="ganador-numero">🏆 ${p.ganador}</div><div class="premios-grid"><div><b>2 primeras: ${p.primeras}</b><span>${esc($("cfgPremioPrimeras")?.value||"Sin valor")}</span><small>${a?`👤 ${esc(a.nombre)} — ${esc(a.telefono)}`:'Sin reserva registrada'}</small></div><div><b>2 del medio: ${p.medio}</b><span>${esc($("cfgPremioMedio")?.value||"Sin valor")}</span><small>${b?`👤 ${esc(b.nombre)} — ${esc(b.telefono)}`:'Sin reserva registrada'}</small></div><div><b>2 últimas: ${p.ultimas}</b><span>${esc($("cfgPremioUltimas")?.value||"Sin valor")}</span><small>${c?`👤 ${esc(c.nombre)} — ${esc(c.telefono)}`:'Sin reserva registrada'}</small></div></div>`}
async function guardarSoloPremios(){const g=$("cfgGanador").value.replace(/\D/g,"").slice(0,4);if(g.length!==4){msg("⚠️ El número ganador debe tener 4 cifras.","error");return}try{await db.collection("config").doc("premios").set({ganador:g,primeras:$("cfgPremioPrimeras").value.trim(),medio:$("cfgPremioMedio").value.trim(),ultimas:$("cfgPremioUltimas").value.trim()},{merge:true});mostrarResultadoGanador();msg("🏆 Número ganador y premios guardados.")}catch(e){console.error(e);msg("❌ No se pudieron guardar los premios.","error")}}

async function migrarRifaAnterior(){
  // Conserva las reservas que la V6 anterior guardaba en /rifa.
  // Solo se ejecuta una vez y las copia a la modalidad normal /rifa_normal.
  try{
    const marca=await db.collection("config").doc("migracion_independencia").get();
    if(marca.exists && marca.data().completada===true)return;
    const anterior=await db.collection("rifa").get();
    if(!anterior.empty){
      const destino= db.collection("rifa_normal");
      const existentes=await destino.get();
      const ids=new Set(existentes.docs.map(d=>d.id));
      let batch=db.batch(),count=0;
      for(const d of anterior.docs){
        if(ids.has(d.id))continue;
        batch.set(destino.doc(d.id),d.data());
        count++;
        if(count===450){await batch.commit();batch=db.batch();count=0;}
      }
      if(count)await batch.commit();
      msg(`✅ Se conservaron ${anterior.size} registros de la versión anterior en Rifa 00–99.`);
    }
    await db.collection("config").doc("migracion_independencia").set({completada:true,fecha:firebase.firestore.Timestamp.now()},{merge:true});
  }catch(e){
    console.error("Migración V6:",e);
    msg("⚠️ No se pudo completar automáticamente la migración de las reservas anteriores. No se borró ningún dato.","error");
  }
}

function nombreModalidad(){return tipo==="mini"?"Rifa 0–9":tipo==="combo"?"Rifa de combos":"Rifa 00–99"}
async function reiniciarRifa(){if(!confirm("⚠️ Esto borrará TODAS las reservas y pagos actuales. ¿Continuar?"))return;try{const s=await db.collection(coleccionRifa()).get();const docs=s.docs;for(let i=0;i<docs.length;i+=450){const batch=db.batch();docs.slice(i,i+450).forEach(d=>batch.delete(d.ref));await batch.commit()}if(tipo==="combo") await db.collection("config").doc("combos").delete();msg(`🔥 ${nombreModalidad()} reiniciada: reservas y pagos eliminados.`);}catch(e){console.error(e);msg("❌ No se pudo reiniciar la rifa.","error")}}
async function reiniciarTalonario(){if(!confirm("⚠️ Se borrarán las reservas actuales y se generará de nuevo el talonario. ¿Continuar?"))return;try{const s=await db.collection(coleccionRifa()).get();for(let i=0;i<s.docs.length;i+=450){const batch=db.batch();s.docs.slice(i,i+450).forEach(d=>batch.delete(d.ref));await batch.commit()}if(tipo==="combo"){const lista=generarCombos();comboLista=lista;await db.collection("config").doc("combos").set({lista})}msg("🎟️ Talonario reiniciado correctamente.");setTimeout(()=>location.reload(),350)}catch(e){console.error(e);msg("❌ No se pudo reiniciar el talonario.","error")}}
function generarCombos(){const altos=Array.from({length:49},(_,i)=>i+51).sort(()=>Math.random()-.5),bajos=Array.from({length:51},(_,i)=>i).sort(()=>Math.random()-.5),lista=[];for(let i=0;i<50;i++)lista.push(`${String(bajos[i]).padStart(2,"0")} - ${String(altos[i%altos.length]).padStart(2,"0")}`);return lista}
function eventos(){paneles();$("filtroNumeros")?.addEventListener("change",renderNumeros);$("filtroPagos")?.addEventListener("change",renderPagos);$("buscarComprador")?.addEventListener("input",renderCompradores);$("configForm")?.addEventListener("submit",guardarConfig);$("btnRecargarConfig")?.addEventListener("click",()=>cargarConfig().catch(console.error));$("btnActualizar")?.addEventListener("click",render);$("btnReiniciarRifa")?.addEventListener("click",reiniciarRifa);$("btnReiniciarTalonario")?.addEventListener("click",reiniciarTalonario);$("btnGuardarPremios")?.addEventListener("click",guardarSoloPremios);$("cfgGanador")?.addEventListener("input",mostrarResultadoGanador);$("cfgPremioPrimeras")?.addEventListener("input",mostrarResultadoGanador);$("cfgPremioMedio")?.addEventListener("input",mostrarResultadoGanador);$("cfgPremioUltimas")?.addEventListener("input",mostrarResultadoGanador);document.addEventListener("click",e=>{const l=e.target.closest(".btn-liberar"),p=e.target.closest(".btn-pago");if(l)liberar(l.dataset.id);if(p)cambiarPago(p.dataset.id)})}
async function iniciarPanel(){if(unsubscribe)return;eventos();try{await cargarConfig();await migrarRifaAnterior();escucharRifa()}catch(e){console.error(e);msg("❌ No se pudo cargar la configuración.","error")}}
if(typeof firebase==="undefined"||!firebase.auth){showLogin();error("Firebase Authentication no está disponible.");return}
firebase.auth().onAuthStateChanged(async u=>{authChecked=true;if(!u){showLogin();return}if(u.uid!==ADMIN_UID){await firebase.auth().signOut();showLogin();error("Esta cuenta no tiene permisos de administrador.");return}showAdmin(u)});setTimeout(()=>{if(!authChecked)showLogin()},7000);
})();
