"use strict";
let seleccionados=new Set(),TIPO_TALONARIO="normal",CONFIG={nequi:"3003704654",whatsapp:"3003704654"},unsubscribeRifa=null,bloqueando=false;
const MAX_SELECCIONADOS=20,$=id=>document.getElementById(id),grid=$("grid");
function normalizarTelefono(n){let x=String(n||"").replace(/\D/g,"");if(x.startsWith("57")&&x.length>10)x=x.slice(2);return x}
function toast(m,t="ok"){const x=$("toast");if(!x)return;x.textContent=m;x.className="show "+t;clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.className="",4000)}
function estado(m,t=""){$("estadoConexion").textContent=m;$(`estadoConexion`).className="estado-conexion "+t}
function contador(){const n=seleccionados.size;$("contadorSeleccion").textContent=`${n} seleccionado${n===1?"":"s"} / ${MAX_SELECCIONADOS} máximo`;$("resumenSeleccion").textContent=n?`🎟️ Números seleccionados: ${[...seleccionados].sort().join(", ")}`:"";$("btnReservar").disabled=!n}
function crearCasilla(txt){const b=document.createElement("button");b.type="button";b.className="numero";b.textContent=txt;b.dataset.numero=txt;b.onclick=()=>seleccionar(b,txt);grid.appendChild(b)}
async function generarGrid(){if(unsubscribeRifa){unsubscribeRifa();unsubscribeRifa=null}grid.innerHTML="";seleccionados.clear();contador();if(TIPO_TALONARIO==="mini"){for(let i=0;i<10;i++)crearCasilla(String(i))}else if(TIPO_TALONARIO==="combo"){let lista;try{const d=await db.collection("config").doc("combos").get();lista=d.exists&&Array.isArray(d.data().lista)?d.data().lista:Array.from({length:50},(_,i)=>`${String(i*2).padStart(2,"0")} - ${String(i*2+1).padStart(2,"0")}`)}catch(e){lista=[]}lista.forEach(x=>crearCasilla(String(x)))}else{for(let i=0;i<100;i++)crearCasilla(String(i).padStart(2,"0"))}activarTiempoReal()}
function seleccionar(el,n){if(bloqueando)return;if(el.classList.contains("ocupado")){toast("❌ Ese número ya está ocupado.","error");return}if(seleccionados.has(n)){seleccionados.delete(n);el.classList.remove("seleccionado")}else{if(seleccionados.size>=MAX_SELECCIONADOS){toast(`⚠️ Máximo ${MAX_SELECCIONADOS} números.`,`error`);return}seleccionados.add(n);el.classList.add("seleccionado")}contador()}
function mostrarFormulario(){if(!seleccionados.size){toast("Selecciona al menos un número.","error");return}$("formulario").classList.remove("oculto");contador();setTimeout(()=>$("nombre")?.focus({preventScroll:true}),50)}
function cerrarFormulario(){$("formulario").classList.add("oculto")}
function validar(){const nombre=$("nombre").value.trim(),telefono=normalizarTelefono($("telefono").value);if(nombre.length<2){toast("Escribe tu nombre.","error");return null}if(telefono.length<7||telefono.length>10){toast("Escribe un teléfono válido.","error");return null}if(!seleccionados.size){toast("No hay números seleccionados.","error");return null}return{nombre,telefono}}
function wa(nombre,numeros,tel){const destino=normalizarTelefono(CONFIG.whatsapp);const msg=[`Hola, soy ${nombre}.`,`Reservé los números: ${numeros}.`,`Mi teléfono es: ${tel}.`,`Quedo atento para el pago.`].join("\n");return `https://wa.me/57${destino}?text=${encodeURIComponent(msg)}`}
async function confirmarReserva(){if(bloqueando)return;const datos=validar();if(!datos)return;const btn=$("btnConfirmar"),original=btn.textContent;bloqueando=true;btn.disabled=true;btn.textContent="⏳ Reservando...";const numeros=[...seleccionados];try{await db.runTransaction(async tx=>{const refs=numeros.map(n=>db.collection("rifa").doc(n)),docs=[];for(const r of refs)docs.push(await tx.get(r));const ocupado=docs.find(d=>d.exists);if(ocupado)throw new Error(`NUMERO_OCUPADO:${ocupado.id}`);const fecha=firebase.firestore.Timestamp.now();refs.forEach((r,i)=>tx.set(r,{nombre:datos.nombre,telefono:datos.telefono,numero:numeros[i],fecha,pagado:false}))});const lista=[...numeros].sort().join(", "),url=wa(datos.nombre,lista,datos.telefono);seleccionados.clear();document.querySelectorAll(".numero.seleccionado").forEach(e=>e.classList.remove("seleccionado"));$("formulario").classList.add("oculto");$("nombre").value="";$("telefono").value="";$("resultadoTexto").textContent=`Reservaste: ${lista}. Tu reserva quedó registrada. Confirma por WhatsApp.`;$("btnWhatsAppReserva").href=url;$("resultadoReserva").classList.remove("oculto");contador();toast("✅ Reserva realizada correctamente.");setTimeout(()=>window.location.assign(url),150)}catch(e){console.error(e);let mensaje = "No se pudo completar la reserva. Revisa tu conexión e inténtalo nuevamente.";
if(e.message?.startsWith("NUMERO_OCUPADO:")){
  mensaje = `❌ El número ${e.message.split(":")[1]} acaba de ser ocupado.`;
}else if(e.code === "permission-denied"){
  mensaje = "❌ Firebase rechazó la reserva por las reglas de Firestore. Publica las nuevas reglas del proyecto.";
}else if(e.code === "unavailable"){
  mensaje = "❌ Firebase no está disponible. Revisa tu conexión e inténtalo nuevamente.";
}else if(e.code === "failed-precondition"){
  mensaje = "❌ Firestore no está listo o hay una configuración pendiente.";
}
console.error("Código Firebase:", e.code, "Mensaje:", e.message);
toast(mensaje,"error")}finally{bloqueando=false;btn.disabled=false;btn.textContent=original}}
function actualizarBarra(v){const total=document.querySelectorAll(".numero").length,p=total?Math.min(100,Math.round(v/total*100)):0;$("barra").style.width=p+"%";$("texto-barra").textContent=`${p}% vendido (${v}/${total})`}
function activarTiempoReal(){unsubscribeRifa=db.collection("rifa").onSnapshot(s=>{const map=new Map();s.forEach(d=>map.set(d.id,d.data()));document.querySelectorAll(".numero").forEach(el=>{const d=map.get(el.dataset.numero);el.classList.remove("ocupado","pagado");if(d){el.classList.add("ocupado");if(d.pagado===true)el.classList.add("pagado");if(seleccionados.has(el.dataset.numero)){seleccionados.delete(el.dataset.numero);el.classList.remove("seleccionado")}}});contador();actualizarBarra(s.size);estado("🟢 Conectado en tiempo real","ok")},e=>{console.error(e);estado("🔴 Error de conexión","error");toast("No se pudo actualizar la rifa en tiempo real.","error")})}
async function copiarNequi(){try{await navigator.clipboard.writeText(CONFIG.nequi);toast(`📋 Nequi copiado: ${CONFIG.nequi}`)}catch(e){toast(`Número Nequi: ${CONFIG.nequi}`,"error")}}
function enviarComprobante(){const t=normalizarTelefono(CONFIG.whatsapp);if(t.length<7){toast("El WhatsApp no está configurado.","error");return}window.location.assign(`https://wa.me/57${t}?text=${encodeURIComponent("Hola, envío comprobante de pago.")}`)}
async function cargar(){try{estado("🟡 Conectando...");const c=await db.collection("config").doc("datos").get();if(c.exists)CONFIG={...CONFIG,...c.data()};const t=await db.collection("config").doc("talonario").get();if(t.exists)TIPO_TALONARIO=t.data().tipo||"normal";await generarGrid();const x=await db.collection("config").doc("texto").get();if(x.exists&&x.data().html)$("info-sorteo").innerHTML=x.data().html;estado("🟢 Conectado","ok")}catch(e){console.error(e);estado("🔴 No se pudo conectar con Firebase","error");toast("No se pudo cargar la rifa.","error")}}
$("btnReservar")?.addEventListener("click",mostrarFormulario);$("btnCancelar")?.addEventListener("click",cerrarFormulario);$("btnConfirmar")?.addEventListener("click",confirmarReserva);$("btnCopiarNequi")?.addEventListener("click",copiarNequi);$("btnComprobante")?.addEventListener("click",enviarComprobante);window.addEventListener("online",()=>estado("🟢 Internet disponible","ok"));window.addEventListener("offline",()=>{estado("🔴 Sin conexión","error");toast("Estás sin conexión a internet.","error")});cargar();
